### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by popey** [xxhomey19/nba-go#10]
Trying to build nba-go from source, but I get this:-

```
npm ERR! path /root/build_nba-go/parts/nba-go/install/lib/node_modules/nba-go/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/root/build_nba-go/parts/nba-go/install/lib/node_modules/nba-go/lib/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Is this possibly related to https://github.com/xxhomey19/nba-go/commit/7c70fab151e7e01d4bca640bfa20d933dd3b05bf with files being in the wrong directory?

**Comment by lifayt** [comment]
Building from source:

`yarn build`

Then from the root directory, you can run:

`node lib/cli.js <command>` 

and you will see whatever changes you've made.

**Comment by popey** [comment]
Thanks for the prompt reply! I cloned it from github and built it. I'm trying to build a snap [1] for upload to the snap store, to make it easy for Linux users to get hold of your app. I've not used yarn with snapcraft before, so talking to our expert @elopio about it.  

[1] - http://snapcraft.io/
