### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by purezhi** [xxhomey19/nba-go#24]
when i install it with `npm install nba-go -g`, i got errors as follows,

> npm ERR! Unexpected end of JSON input while parsing near '...-/babel-generator-6.4'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/david/.npm/_logs/2017-11-08T10_45_44_777Z-debug.log

> $ node -v 
> v8.9.1
> $ npm -v
> 5.5.1

any tips?
thx.

**Comment by xxhomey19** [comment]
Hi @purezhi ,
I think this is not a problem with nba-go.
Try to upgrade or downgrade node and npm. This might work.

**Comment by purezhi** [comment]
@xxhomey19 thx, i succeed after executing `npm cache clean --force`.
