### ISSUE TITLE
 jet lag

### ISSUE THREAD

**Issue by jwz-ecust** [xxhomey19/nba-go#28]
Did not consider the issue of jet lag.

**Comment by xxhomey19** [comment]
Hi @jwz-ecust ,
it seems similar to #2

**Comment by cagross** [comment]
Can you clarify what you mean by the issue of jet lag?  Are you referencing the issue that arises because not all users will be in the same time zone, therefore 'today's games' are different for different users?

**Comment by jwz-ecust** [comment]
@cagross  Acutally, time difference between the United States and China makes me confused.

**Comment by cagross** [comment]
OK right, I agree. I live in Thailand, so I also notice the issue.  As Homer mentioned, that is something I am trying to resolve with [issue #2](https://github.com/xxhomey19/nba-go/issues/2) .

**Comment by jwz-ecust** [comment]
@cagross @xxhomey19  Thanks!🍺
