### ISSUE TITLE
Default param

### ISSUE THREAD

**Issue by switz** [xxhomey19/nba-go#31]
Would be really nice if just running `nba-go` defaulted to `nba-go game`. Happy to send a PR if you're open to it.

Thanks for a really cool util!

**Comment by xxhomey19** [comment]
Hi @switz ,
I'm not sure whether setting a default command is a good idea or not. If user enters `nba-go -h`, what it should show? original `nba-go -h` or `nba-go game -h`?
Actually, if nba-go need a default command, I prefer just use `nba-go game -t`.
Hope for more discussion.

**Comment by xxhomey19** [comment]
I prefer to show help description than `nba-go game`.
Reopen this issue if there is a better suggestion.
