### ISSUE TITLE
Listing all commands 

### ISSUE THREAD

**Issue by fenek5** [xxhomey19/nba-go#37]
It would be really great to just type  (FEAUTURE)

`$ nba-go`

 and to see all the commands available with a simple description of what they do. 

and why not display current ranking table

**Comment by xxhomey19** [comment]
Hi @fenek5 ,
this will be nice, but it seems duplicated with `nba-go --help`? Do you means it should show `--help` when user doesn't enter any option or command?

**Comment by fenek5** [comment]
Yes it is what I mean, Oh I'm sorry I didn't seen it.

**Comment by xxhomey19** [comment]
It's OK!
To be frank, this is a good suggestion. Maybe you could try to let it show `--help` when nothing comes after `nba-go` and send a PR!
