### ISSUE TITLE
Highlighting game highs for each category

### ISSUE THREAD

**Issue by ChristianLapinig** [xxhomey19/nba-go#43]
In the team box score, I know that it highlights the play with the most points as shown below

![screenshot from 2017-11-12 22-22-48](https://user-images.githubusercontent.com/11323135/32712242-5eff359a-c7f8-11e7-9217-ccae709855f3.png)

I was wondering if highlighting the high of each category would be cool.

**Comment by xxhomey19** [comment]
Hi @ChristianLapinig ,
well, actually, each category will be highlighted when its number is over its own standard (I decided the standard). For instance, MIN is 35, +/- is 15 and PTS is 20.
I'm not sure whether this is a good way or not. Maybe people want to highlight the highest number of each category. This could have more discussions.

**Comment by jhamet93** [comment]
Personally, If I'm scanning the box score I would want the highest in each category highlighted. Not sure a hardcoded threshold is obvious to end users.

**Comment by ChristianLapinig** [comment]
@xxhomey19 I or someone can work on this and send a PR if it's ok with you.

**Comment by xxhomey19** [comment]
@ChristianLapinig 

Sure, it's fine with me.

**Comment by xxhomey19** [comment]
#51
