### ISSUE TITLE
Does this program require a GUI

### ISSUE THREAD

**Issue by 14u2ponder** [xxhomey19/nba-go#71]
I am just asking because I run a shell-only enviornment and this requires me to install node.js so I'd like to know if node.js requires X, X server, or something else to work.

**Comment by xxhomey19** [comment]
I think it only needs `Node.js` and `npm`. Otherwise, you can run it by docker or download pkg files. Check [install section](https://github.com/xxhomey19/nba-go#install) in README.

**Comment by xxhomey19** [comment]
@14u2ponder 
Hey I just release a menubar app called [NBA Bar](https://github.com/xxhomey19/nba-bar). It has a better GUI and easy to use. It doesn't need any dependencies, just download .dmg or .exe file, then you can use it. Hope this could help.
