### ISSUE TITLE
Tiny bug

### ISSUE THREAD

**Issue by JacobEvelyn** [xxhomey19/nba-go#9]
Hey! This looks really neat. I haven't looked into the code at all so apologies if this is already fixed, but I figured I'd let you know that in the README this gif says "Seth Seth" instead of "Seth Curry." Not sure if that bug is elsewhere or not.

![player -p gif](https://user-images.githubusercontent.com/12113222/32416909-03e46ea8-c28c-11e7-84af-4b40895d2054.gif)

Hope that's helpful, and good luck!

**Comment by xxhomey19** [comment]
Thanks for your notification!
I just fixed this bug few hours ago, but I forgot to change the GIF file in README haha.
I'll fix it.
